
platform :ios, '8.0'

target 'ReactNativeDemo' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'DevSupport',
    # Add any other subspecs you want to use in your project
  ]
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
end
